databases:
  - name: pizzas
    databaseName: pizzas
    user: pizzas

services:
  - type: web
    name: pizzas
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pizzas
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
